import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import {
  Activity,
  ArrowRight,
  Baby,
  CalendarDays,
  ChevronDown,
  CircleAlert,
  CircleCheck,
  Cloud,
  Clock3,
  Download,
  FileUp,
  Focus,
  GitFork,
  Heart,
  Info,
  Layers3,
  LUCIDE_ICONS,
  ListChecks,
  LogIn,
  LogOut,
  LucideIconProvider,
  Mail,
  Menu,
  MapPin,
  Pencil,
  Plus,
  Redo2,
  Save,
  Search,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Skull,
  Trash2,
  TriangleAlert,
  Undo2,
  Upload,
  UploadCloud,
  User,
  UserRoundSearch,
  Wrench,
  X,
  ZoomIn,
  ZoomOut
} from 'lucide-angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider({
        Activity,
        ArrowRight,
        Baby,
        CalendarDays,
        ChevronDown,
        CircleAlert,
        CircleCheck,
        Cloud,
        Clock3,
        Download,
        FileUp,
        Focus,
        GitFork,
        Heart,
        Info,
        Layers3,
        LogIn,
        LogOut,
        ListChecks,
        Mail,
        Menu,
        MapPin,
        Pencil,
        Plus,
        Redo2,
        Save,
        Search,
        ShieldCheck,
        SlidersHorizontal,
        Sparkles,
        Skull,
        Trash2,
        TriangleAlert,
        Undo2,
        Upload,
        UploadCloud,
        User,
        UserRoundSearch,
        Wrench,
        X,
        ZoomIn,
        ZoomOut
      })
    }
  ]
};
